# Generated by Django 5.0.4 on 2024-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section_topic',
            field=models.CharField(choices=[('Announcement', 'announcement'), ('Event', 'event'), ('Post', 'post'), ('Birthday', 'birthday')], default='p', max_length=100),
        ),
    ]
