# Generated by Django 5.0.4 on 2024-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
